import Vue from 'vue'
import req from './BaseHandler.js'
let vue = new Vue()

export default{
    data(){
        return {}
    },
    getActlist(p,str,scb,ecb){
        req.handler(
            vue.$http.get('/act/list',{
            params:{
              "p":p,
              "Searchstr":str
            }}),scb,ecb,ecb
        )  
    },
    getActTotal(str,scb,ecb){
        req.handler(
            vue.$http.get('/act/list/total',{
                params:{
                  "Searchstr":str
            }}),scb,ecb,ecb
        );    
    },
    deleteAct(id,type,scb,ecb){
        req.handler(
            vue.$http.delete('/act/'+id,{
                params:{
                  "type":type
                }
            }),
            scb,ecb,ecb
        ); 
    },
    pushAct(id,type,scb,ecb){
        req.handler(
            vue.$http({
                url:'/act/rec/'+id,
                method:"POST",
                params:{"type":type}
            }),
            scb,ecb,ecb
        ); 
    },
    getActReviewlist(p,str,scb,ecb){
        req.handler(
            vue.$http.get('/act/review/list',{
            params:{
              "p":p,
              "Searchstr":str
            }}),scb,ecb,ecb
        )  
    },
    getActReviewTotal(str,scb,ecb){
        req.handler(
            vue.$http.get('/act/review/list/total',{
                params:{
                  "Searchstr":str
            }}),scb,ecb,ecb
        );    
    },
    getActDetail(id,scb,ecb){
        req.handler(
            vue.$http.get('/act/review/'+id),scb,ecb,ecb
        );    
    },
    setActStatus(id,status,type,scb,ecb){
        req.handler(
            vue.$http(
                {
                  url:'/act/review/'+id,
                  method:status==1?'PUT':'DELETE',
                  params:{'type':type}
                }
              ),scb,ecb,ecb
        );
    },
    getActReclist(p,scb,ecb){
        req.handler(
            vue.$http.get('/act/rec/list',{
            params:{
              "p":p
            }}),scb,ecb,ecb
        )  
    },
    getActRecTotal(scb,ecb){
        req.handler(
            vue.$http.get('/act/rec/list/total'),scb,ecb,ecb
        );    
    },
    deleteActRec(id,scb,ecb){
        req.handler(
            vue.$http.delete('/act/rec/'+id),
            scb,ecb,ecb
        ); 
    }

}